project:
  type: book

book:
  title: "The APDVS Medical Student Curriculum"
  author: "The APDVS and contributors"
  date: "01/31/2023"
  description: "eBook Companion"
  sidebar:
    style: docked
    background: light
  search: true
  downloads: [pdf, epub]
  sharing: [twitter]
  page-navigation: true

  chapters:
    - part: "Introduction"
      chapters: 
        - index.qmd
        - announcement2.qmd
        - authors2.qmd
    
    - part: "Approach to Vascular Patient"
      chapters: 
        - arterial_history_physical.qmd
        
    - part: "Carotid Disorders"
      chapters: 
      - carotid2.qmd
        
    - part: "Aortic Disorders"
      chapters: 
      - AAA2.qmd

    - feedback.qmd
    - references.qmd

  google-analytics: "G-WS28VX4802"
  cookie-consent: true
  open-graph: true
  
number-depth: 2

bibliography: references.bib

format:
  html:
    theme: cosmo
#  pdf:
#    documentclass: scrreprt
#    include-in-header: 
#      text: |
#        \usepackage{makeidx}
#        \makeindex
#    include-after-body: 
#      text: |
#        \printindex

  pdf:
    documentclass: scrreprt

editor: visual

comments: 
  hypothesis: true