---
format: html
editor: visual
number-sections: false
bibliography: references.bib
smooth-scroll: true
link-external-newwindow: true
---

------------------------------------------------------------------------

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-WS28VX4802"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-WS28VX4802');
</script>

# Authors and Contributors {.unnumbered}

This eBook is the result of a partnership between the APDVS and the Audible Bleeding Podcast, each of which is comprised of hard working individuals dedicated to medical education and the promotion of vascular surgery. The authors and contributors of this eBook have freely donated their time and experience to create this resource. Please follow them on twitter or other social media platforms to return this debt of gratitude and to, as Audible Bleeding says, "keep a finger on the pulse."

------------------------------------------------------------------------

### Editors

**Ezra Schwartz, MDCM, MS, MMS.** *Montefiore Medical Center* [\@EzraSchwartz10](https://twitter.com/EzraSchwartz10)

**Yasong Yu, MD.** *Rutgers New Jersey Medical School* [\@YasongYuMD](https://twitter.com/YasongYuMD)

**Chaitanya Dandu, MD.** *Yale School of Medicine* [\@ChaituDandu](https://twitter.com/ChaituDandu)

**Mark Basilious** MS3; *Weill Cornell Medical College* [\@markrbasilious](https://x.com/markrbasilious)

------------------------------------------------------------------------

### Faculty Authors

**Babak Abai, MD, FACS.** Associate Professor of Surgery; Program Director, Vascular Surgery Fellowship; *Thomas Jefferson University* [Academic Profile](https://www.jeffersonhealth.org/find-a-doctor/a/abai-babak) [\@DrBabakAbai](https://twitter.com/DrBabakAbai?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor)

**Jonathan Bath, MD, FACS, DFSVS.** Associate Professor of Surgery; Program Director, Vascular Surgery Fellowship; *University of Missouri School of Medicine* [Academic Profile](https://www.muhealth.org/doctors/jonathan-bath-md) 

**Cassius Iyad Ochoa Chaar, MD, MS, RPVI.** Associate Professor of Surgery; *Yale School of Medicine* [Academic Profile](https://medicine.yale.edu/profile/cassius-chaar/) [\@MdChaar](https://twitter.com/MdChaar)

**Dawn Coleman, MD, FACS.** Chief, Division of Vascular and Endovascular Surgery;  *Duke University School of Medicine* [Academic Profile](https://surgery.duke.edu/profile/dawn-m-coleman) [\@ColemanDM_vasc](https://twitter.com/ColemanDM_vasc)

**Sharif Ellozy, MD.**  G. Tom Shires Faculty Scholar in Surgery, Associate Professor of Clinical Surgery, Program Director of the Vascular Surgery Fellowship; *Weill Cornell Medical College* [Academic Profile](https://weillcornell.org/sellozy)[\@SharifEllozy](https://twitter.com/SharifEllozy)

**Erin Greenleaf, MD, MS, RPVI** Assistant Professor; *Baylor College of Medicine* [Academic Profile](https://www.bcm.edu/people-search/erin-greenleaf-90476)

**Angela Kokkosis, MD, FACS.** Associate Professor of Surgery; Program Director, Vascular and Endovascular Residency; Director, Carotid Interventions; Co-Medical Director, Non-Invasive Vascular Laboratory; *Stony Brook University* [Academic Profile](https://renaissance.stonybrookmedicine.edu/surgery/people/faculty/dr-angela-a-kokkosis) [\@Angela_Kokkosis](https://twitter.com/Angela_Kokkosis)

**Loay S Kabbani, MD, MHSA, FACS.** Program Director, Vascular Surgery Fellowship; *Henry Ford Health* [Academic Profile](https://www.henryford.com/physician-directory/k/kabbani-loay) [\@loaykabbani](https://twitter.com/loaykabbani)

**Michael Malinowski, MD, MEHP, FACS.** Associate Professor; *Medical College of Wisconsin, Froedert Hospital* [Academic Profile](https://www.froedtert.com/doctors/michael-malinowski-1316100860)

**Daniel Torrent, MD, MPH, FACS.** Vascular Surgeon; *Northeast Georgia Health System* [Profile](https://www.longstreetclinic.com/providers/daniel-torrent/)

------------------------------------------------------------------------

### Trainee Authors

**Marvin Chau, MD.** Integrated Vascular Surgery Resident; *UCLA Health* [Academic Profile](https://www.uclahealth.org/departments/surgery/education/residency/vascular-surgery-residency-program/residents-fellows)[\@MChau_MD](https://twitter.com/MChau_MD)

**Nakia Sarad, DO, MS.** General Surgery Resident, Vascular Surgery Research Fellow; *Weill Cornell Medicine* [Academic Profile](https://www.nyp.org/queens/graduate-medical-education/surgery/current-residents) [\@NakSaradDO](https://twitter.com/NakSaradDO)

**Sree Kannathasan, MD.** Integrated Vascular Surgery Resident; *McGill University* [\@VulnerableAorta](https://twitter.com/VulnerableAorta)

**Regis Hila, MD.** General Surgery Resident; *Northwell Health* [\@HilaRegis](https://twitter.com/HilaRegis)

**Emily Goodman, MD.** Vascular Surgery Fellow; *The University of Chicago* [Academic Profile](https://surgery.uchicago.edu/education/vascular-surgery-fellowship) [\@emily_goodmanMD](https://twitter.com/emily_goodmanMD)

**Raj S. Lingnurkar, MD.** General Surgery Resident; *Trinity Health Mid-Atlantic*  [\@rslingnurkar](https://twitter.com/rslingnurkar)

**Joseph Yoo, MD.** Integrated Vascular Surgery Resident; *Jefferson Health / Einstein Healthcare Network* [Academic Profile](https://www.jeffersonhealth.org/about-us/academic-programs/graduate-medical-education/residency-programs/integrated-vascular-surgery-einstein-montgomery/residents)

**Abena Appah-Sampong, MD.** General Surgery Resident; *Brigham and Women's Hospital* [\@AbenaSamp](https://twitter.com/AbenaSamp)

**Nitin Jethmalani, MD.** General Surgery Resident, Vascular Surgery Research Fellow; *Weill Cornell Medicine* [\@nijethmalani](https://x.com/nijethmalani)

**Lucas Canaan, DO.** General Surgery Resident; *Northeast Georgia Health System* [Academic Profile](https://www.ngmcgme.org/resident/lucas-canaan-do/)

------------------------------------------------------------------------

### Student Contributors

**Ivana Zhang** MS4; *Jacobs School of Medicine And Biomedical Sciences at University at Buffalo*

**Shannon McDonnell** MS4; *Stritch School of Medicine at Loyola University Chicago*

**Jeremy Zack** MS4; *Sidney Kimmel Medical College* [LinkedIn](https://www.linkedin.com/in/jeremy-zack/)

------------------------------------------------------------------------

### Medical Illustrators

**Ivana Zhang** MS4; *Jacobs School Of Medicine And Biomedical Sciences at University at Buffalo*

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-WS28VX4802"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-WS28VX4802');
</script>
