---
title: "Carotid Artery Stenosis"
chapter_number: 3
title-block-banner: false
title-block-style: plain
authors: Angela Kokkosis, MD, FACS and Michael Malinowski, MD, MEHP, FACS
format: html
editor: visual
number-sections: false
bibliography: references.bib
smooth-scroll: true
link-external-newwindow: true
---

#  {#sec-carotidarterystenosis}

::: {.callout-note icon="false"}
## Chapter Learning Objectives

By the end of this chapter, students will:

-   Review the foundational knowledge to appraise asymptomatic and symptomatic carotid artery stenosis.
-   Identify and describe risk factors, symptoms, and signs of carotid artery disease.
-   Review and describe indications and contraindications for medical and surgical management of carotid artery stenosis.
-   Propose next best steps in patient work-up and treatment of carotid artery disease.
-   Describe the evidence-based outcomes of surgical management of carotid artery disease.
:::

::: {.callout-note icon="false"}
## Key Facts

1.  Stroke is the leading cause of disability nationally and 3rd leading cause of death with a breakdown of 80% occlusive (ischemic) and 20% hemorrhagic.
2.  Symptomatic carotid stenosis presents with only three symptoms including: stroke, transient ischemic attack (TIA) and amaurosis fugax (transient retinal ischemia).
3.  Risk factors include: age, smoking, CAD, diabetes, hypertension, hyperlipidemia and genetic/family history.
4.  Seminal studies include ACAS and NASCET. They define an 11% five-year risk of stroke for asymptomatic carotid artery stenosis (\>60%) and 24% two-year risk of stroke for symptomatic disease (\>70%), respectively.
5.  The CREST landmark study associates carotid artery stenting with higher perioperative risk of stroke and carotid endarterectomy (CEA) with higher risk of myocardial infarction (MI) in symptomatic patients.
6.  Carotid artery stenting (CAS) is indicated for recurrent stenosis after CEA, neck immobility, high carotid bifurcation, contralateral occlusion, high risk open surgical candidate due to cardiopulmonary comorbidity and neck radiation.
7.  Transcarotid artery revascularization (TCAR) is available for direct common carotid delivery of stent while avoiding aortic arch manipulation and providing embolic protection through flow reversal.
8.  There is a marginal benefit for intervention for asymptomatic carotid artery stenosis patients with significant cardiopulmonary disease due to risks of associated perioperative events.
:::

::: {.callout-warning icon="false"}
## Carotid Disease Slide Deck

Please find the slide deck corresponding to this eBook chapter [**here**.](https://docs.google.com/presentation/d/1sySy69sCXjZni1pJkoXCbh5bCYopTBQg/edit?usp=sharing&ouid=103498724122494401400&rtpof=true&sd=true)

Please find a video recording of Dr. Kokkosis and Dr. Malinowski's lecture using the above slide deck [**here**.](https://drive.google.com/file/d/1OkN4dh0gVoXpoFglnfZc6ARRI0XbREoV/view?usp=sharing)
:::

::: callout-tip
## How We Suggest Using the Pre/Post Questions

The pre/post questions are listed below. They are all multiple choice questions with a single right answer. To best guide your learning, we have hidden the answers in a collapsible menu. Before reading the chapter, we suggest giving the questions a try, noting your answers on a notepad. After reading the chapter, return to the questions, re-evaluate your answers, and then open the collapsible menu to read the correct answer and discussion. Do not fret if you have difficulty answering the questions before reading the chapter! By the end of the chapter, we are certain you will have covered the knowledge necessary to answer the questions. There will be a teaching case at the end of the chapter. This is another opportunity to exercise your new knowledge!
:::

## Pre/Post Questions

### Case Based Questions

1.  A 75-year-old male smoke presents with recent visual changes to his right eye that occurred yesterday. The patient reports a shading of his visual field that resulted in momentary monocular blindness followed by return to normal vision. He has a carotid duplex showing \>50% diameter reduction to his right internal carotid artery and \>80% stenosis to his left internal carotid artery. *What treatment should be offered to his patient?*

A. Emergent DC cardioversion to treat any underlying arrythmia.

B. Left carotid endarterectomy with shunt placement.

C. Left carotid TCAR.

D. Right carotid endarterectomy.

E. Placement on Apixaban and measurement of PF4 with medical management.

::: {.callout-note icon="false" collapse="true"}
## Answer

**D. Right carotid endarterectomy**

Discussion: The patient has evidence of amaurosis fugax with temporary monocular blindness as a sign of symptomatic right internal carotid artery disease. His left carotid artery is in a high-grade range and therefore is lower risk of stroke than the contralateral symptomatic lesion. There should be no immediate surgical treatment of the asymptomatic left carotid lesion. There is no evidence that the patient has an underlying arrythmia that needs cardioversion and medical management with Apixaban and PF4 levels are unrelated to this patient's current pathology.
:::

2.  A 50-year-old female patient with \>80% right internal carotid artery stenosis presents to clinic for her first postoperative visit after carotid endarterectomy (CEA). She has no interval neurologic events since her discharge, has a soft neck with a clean incision. During your neurologic exam you notice an unintentional, subtle tongue deviation to the side of surgery. *What is the most likely facial nerve involved in this finding?*

A. Vagus Nerve.

B. Hypoglossal Nerve.

C. Glossopharyngeal Nerve.

D. Long Thoracic Nerve.

E. Hering's Nerve.

::: {.callout-note icon="false" collapse="true"}
## Answer

**B. Hypoglossal Nerve**

Discussion: This patient has evidence of hypoglossal nerve neuropraxia which can occur as the result of injury or traction on the nerve during distal dissection of the internal carotid artery. Although both glossopharyngeal nerve injury and vagal injuries can also occur during CEA, the former causes oropharyngeal dysfunction with swallowing and the latter causes vocal cord paralysis leading to a hoarse voice. The long thoracic nerve is more related to thoracic outlet surgery and innervation of the serratus anterior. The Nerve of Hering is related to carotid sinus innervation and is unrelated to this clinical finding.
:::

3.  During the initial evaluation of a patient with high grade symptomatic carotid disease, you notice that the patient has internal carotid plaque on that side this is above the angle of the mandible at the 1st cervical vertebral body (C1). This appears to be too high to access through open surgery. The patient has no know history of coronary artery disease, has a preserved ejection fraction and good functional status. He has a low-density lipoprotein level (LDL) of 200 mg/dL. *What is the best treatment option for this individual?*

A. Transfemoral carotid artery angioplasty with placement on ASA only.

B. Carotid artery enterectomy with shunt placement.

C. Daily ASA therapy without any type of statin or antihypertensive therapy.

D. Trancarotid artery revascularization (TCAR) surgery with dual antiplatelet therapy.

E. No treatment is indicated.

::: {.callout-note icon="false" collapse="true"}
## Answer

**D. Transcarotid artery revascularization surgery with dual antiplatelet therapy.**

Discussion: This patient has symptomatic carotid stenosis with an overall optimal coronary health. Because his lesion is high at C1 and not surgically accessible, they would not qualify for a traditional carotid endarterectomy. Transfemoral carotid artery angioplasty is not indicated without stent placement, and daily ASA therapy without statin treatment for an LDL of 200mg/dL does not qualify as optimal medical management. Surgical treatment is indicated in this symptomatic patient since he has no significant cardiopulmonary disease and TCAR is the only option listed that could accomplish this outcome successfully.
:::

4.  A 60-year-old otherwise healthy woman, with no underlying comorbidities has a right carotid artery bruit on physical examination. She is concerned that she is at risk for stroke. She denies any episodes of vision changes, upper or lower extremity deficits, or speech impairments. She currently takes 81mg of aspirin daily, along with a multivitamin. *What is the next step in management for this patient?*

<!-- -->

A.  No further treatment necessary.

B.  Carotid duplex.

C.  CT angiogram head and neck.

D.  Neurology evaluation.

E.  Addition of statin therapy.

::: {.callout-note icon="false" collapse="true"}
## Answer

**A. No further treatment necessary.**

Discussion: This patient has an incidental finding of a carotid bruit on physical exam, however she has no risk factors for carotid disease (such as smoking, hyperlipidemia, smoking, family history, diabetes or hypertension). Additionally, she is neurologically asymptomatic. Therefore, carotid duplex, CTA, neurology evaluation, and the addition of statin therapy are not indicated. The prevalence of \>75% carotid stenosis for those with a carotid bruit has been found to be very low at 1.2%.
:::

5.  A 65-year-old man who is right-handed is undergoing evaluation for a coronary artery bypass graft surgery (CABG). As part of his workup, a carotid duplex is performed which demonstrates a chronic right carotid occlusion and a \>80% stenosis of his left carotid artery. He has no history of ocular or cerebrovascular events. He has hypercholesterolemia and well-controlled hypertension. *What is the next best step for this patient?*

<!-- -->

A.  Proceed with the CABG as planned and continue medical therapy with aspirin and statin.

B.  Left carotid endarterectomy before the CABG.

C.  Place the patient on dual antiplatelet therapy, in addition to statin therapy.

D.  Left TCAR (transcarotid stent) after the CABG.

E.  Place the patient on anticoagulation.

::: {.callout-note icon="false" collapse="true"}
## Answer

**B. Left carotid endarterectomy before CABG.**

Discussion: It is standard of care to assess the carotid arteries prior to performing a CABG, with the goal of minimizing the risk of perioperative stroke. This patient has asymptomatic bilateral severe carotid disease (right occlusion and left \>80% stenosis). Therefore, to reduce the risk of perioperative stroke, current guidelines recommend carotid revascularization prior or concomitant with the CABG. The patient does carry one high risk criterion for TCAR (coronary disease requiring revascularization), however this should not be performed after the CABG. Dual antiplatelet therapy is indicated in the event this patient undergoes carotid stenting, however medical management should not be the only management of his carotid disease. Lastly, anticoagulation has no role in atherosclerotic disease, such as carotid disease.
:::

6.  A 55-year-old woman has a past medical history of coronary artery disease status post coronary stenting in 2019, hypertension, hyperlipidemia, and previous smoking history of 60 pack-years. Her cardiologist sends her for a carotid duplex which demonstrates a 50-69% carotid stenosis on the left side, and mild atherosclerosis on the right side. She denies any prior signs or symptoms of stroke or transient ischemic attack. *How should this patient's carotid disease be managed?*

<!-- -->

A.  Left carotid endarterectomy, along with aspirin/statin therapy.

B.  Left transfemoral carotid stent, along with dual antiplatelet/statin therapy.

C.  Aspirin and statin therapy **only**, and routine surveillance carotid duplexes.

D.  Aspirin, statin therapy, blood pressure management, and routine surveillance carotid duplexes.

E.  No further management is indicated.

::: {.callout-note icon="false" collapse="true"}
## Answer

**D. Aspirin, statin therapy, blood pressure management, and routine surveillance carotid duplexes.**

Discussion: This patient has asymptomatic 50-69% left carotid stenosis with the associated risk factors of vascular disease which include hypertension, hyperlipidemia, and smoking history. Medical therapy needs to be employed to reduce these factors, thus a single antiplatelet, statin, and blood pressure medication are indicated. Fortunately, the patient is not a current smoker, however if she was, then smoking cessation counseling would be added to her treatment plan. Carotid revascularization is indicated only for asymptomatic carotid stenosis that is \>70% based on current guidelines.
:::

### Operative Footage Questions

These questions are associated with the carotid endarterectomy (CEA) footage (**short version**) found at the bottom of the chapter.

1.  What is the first muscle layer encountered in a CEA (i.e. the first muscle deep to skin)?

A. Sternocleidomastoid

B. Digastric

C. Platysma

D. Scalene

::: {.callout-note icon="false" collapse="true"}
## Answer

**C. Platysma**

Discussion: The platysma is the most superficial muscle in the neck. It covers most of the anterior and lateral aspect of the neck. It is the first muscle layer encountered in the neck during a CEA. It will be bisected and repaired upon neck closure. While the sternocleidomastoid is superficial, it is deep to the platysma. The sternocleidomastoid is an important landmark as it forms the anterolateral boundary of the carotid triangle. You will dissect along its medial border and retract it laterally in order to access the carotid sheath.The digastric muscle is a small, "two-bellied" muscle located under the mandible. The posterior belly forms the superior border of the carotid triangle. It is often visualized in patients with high carotid bifurcations.The scalene muscles are deep to the sternocleidomastoid muscles and lateral to the cervical spine. They are not manipulated in a CEA.
:::

2.  What structure is **not** found in the carotid sheath?

A. Internal jugular vein

B. External jugular vein

C. Common carotid artery

D. Vagus nerve

::: {.callout-note icon="false" collapse="true"}
## Answer

**B. External jugular vein**

Discussion: The external jugular vein is not in the carotid sheath. It runs superficial to and obliquely across the sternocleidomastoid before passing to the posterior border of the sternocleidomastoid as it descends deep into the neck. The carotid sheath contains the common carotid artery anteromedially, the internal jugular vein anterolaterally, and the vagus nerve posteriorly.
:::

3.  In what order do you **unclamp** the carotid vessels at the end of a carotid endarterectomy?

A. External carotid artery → common carotid artery → internal carotid artery

B. Common carotid artery → internal carotid artery → external carotid artery

C. Internal carotid artery → external carotid artery → common carotid artery

D. Internal carotid artery → common carotid artery → external carotid artery

::: {.callout-note icon="false" collapse="true"}
## Answer

**D. External carotid artery → common carotid artery → internal carotid artery**

Discussion: In conventional CEA, the internal carotid artery (ICA), the common carotid artery (CCA), and the external carotid artery (ECA) are clamped in that order such that any atherosclerotic debris loosened during vessel manipulation and/or clamping embolizes into the ECA where it could cause extracranial ischemia rather than the ICA where it could cause intracranial ischemia (i.e. ischemic stroke). A useful mnemonic to remember the clamping order is **ICE** for **I**CA, **C**CA, and **E**CA. The order when unclamping is the opposite, **ECI**. The rational is similar. By unclamping the ECA first, remaining debris or debris loosened during removal of the clamps will flow up the ECA rather than the ICA. By unclamping the CCA second, and dislodged debris will flow down the open ECA rather than the ICA. The ICA is unclamped last. Options A and B are dangerous as they do not minimize the risk of embolus flowing into the ICA. Option C is simply incorrect.
:::

------------------------------------------------------------------------

## Introduction

Hemispheric stroke related to carotid artery stenosis is a leading cause of both disability and death in the United States. Underlying etiologies for stroke include occlusive or hemorrhagic events with roughly 80% being related to occlusive pathology through embolus or in-situ thrombosis, the remaining 20% attributable to hemorrhage. Roughly 15% of stroke victims have a transient ischemic attack (TIA) that fully resolved prior to a later stroke event. Risk factors for carotid plaque formation are related to age, smoking, coronary artery disease, diabetes, hyperlipidemia, hypertension and family history of stroke. Due to carotid bulb anatomy, the most common area of plaque formation is within the proximal internal carotid artery. As plaque stenosis increases over time, the systolic velocity increases to maintain flow volumes which intensifies shear stress. This shear stress increases likelihood of plaque rupture, platelet aggregation and thromboembolization. There are multiple seminal studies that describe cohort comparisons of asymptomatic and symptomatic carotid artery stenosis with outcomes related to optimal medical management alone or as adjunct to surgical repair. Symptomatic carotid stenosis is described as carotid stenosis \>50% with unilateral stroke, TIA or amaurosis fugax on the side of carotid disease. Amaurosis fugax is historically described as shade coming down across one eye on the side of stenosis to produce partial or complete, painless monocular visual loss related to transient retinal ischemia. Amaurosis fugax may be bilateral in the case of bilateral, symptomatic carotid artery stenosis.

------------------------------------------------------------------------

## Etiology

Atherosclerosis is the most common cause for the development of carotid artery disease. This process is defined by deposition of lipid-laden plaque at the carotid bifurcation, and potentially across a larger territory of the common carotid, external carotid, and internal carotid arteries. This plaque may contain varying degrees of calcification and/or thrombus. The mechanisms by which atherosclerosis at the carotid bifurcation may lead to stroke or TIA are: occlusion (cessation of blood flow to the internal carotid artery) or embolization (plaque debris break off and travel through the internal carotid artery to the brain). There are various risk factors which may contribute to the degree of atherosclerosis and its progression. These include history of cigarette smoking, hyperlipidemia, coronary artery disease, diabetes, hypertension, advanced age, and family history of carotid disease or stroke.

------------------------------------------------------------------------

## Diagnostics and Imaging

Three primary imaging modalities are used to evaluate carotid artery stenosis with the lowest cost option being color flow duplex ultrasound (DSA) that allows a physician to determine peak systolic and end diastolic velocities throughout the carotid bifurcation. Based on the internally validated vascular laboratory criteria of the institution, these velocities can be correlated to ranges of degree of stenosis, with high grade stenosis defined as \>70-80%. Since the modality is based primarily on velocity range, it cannot give exact stenosis such as 66%. The modality can also provide adjunct information about the blood flow waveforms in each arterial segment, as well as whether that flow is laminar or turbulent with utilization of color flow imaging. Limitations of this imaging include technician skill, inability to obtain optimal angle of Doppler interrogation for velocity determination, shadowing from heavily calcified lesions, poor visualization due to patient habitus and tortuosity.

Axial imaging options include both computed tomography angiogram (CTA) and magnetic resonance angiogram (MRA). Both of these options require some form of intra-arterial contrast, either iodinated contrast or gadolinium, respectively. However, they offer a fuller perspective of relevant anatomy and a more precise determination of stenosis within the limitations of the modality, with MRA often overestimating the degree of stenosis due to intrinsic properties of MRA imaging acquisition. Both CTA and MRA, although superior to DSA in determination of exact degree of plaque stenosis and arterial anatomy, sacrifice the physiologic information offered through DSA that speak to flow patterns, flow direction and turbulence. Axial imaging of CTA and MRA can define patency but do not speak to the dynamic nature of blood flow or directionality of flow.

Definitive determination of flow and directionality can be augmented to a carotid artery stenosis workup by diagnostic angiography. This requires femoral artery access and includes contrast administration, as well as a small risk of periprocedural embolization. However, it offers additional physiologic evaluation that might not be present in DSA and that is inherently lacking in CTA and MRA studies.

### Asymptomatic Carotid Atery Stenosis Screening

The 2021 SVS clinical practice guidelines outline the following recommendations. In asymptomatic patients who qualify for carotid artery stenosis screening, duplex ultrasound is the recommended choice over CTA, MRA, or other imaging modalities.

Routine screening is **not recommended** for clinically asymptomatic carotid artery stenosis for individuals **without significant risk factors** for carotid disease.

Screening is **recommended** for clinically **asymptomatic carotid artery stenosis in individuals** with significant risk factors\*\* for carotid disease. High-risk groups include:

-   Patients with lower extremity peripheral artery disease (PAD)
-   Patients undergoing coronary artery bypass surgery (CABG)
-   Patients aged \>= 55 years with at least two traditional atherosclerotic risk factors (hyperlipidemia, hypertension, etc.)
-   Patients aged \>= 55 years and active cigarette smoking
-   Patients with diabetes, hypertension, or coronary artery disease (CAD)
-   Patients with clinically occult cerebral infarction noted on brain imaging studies.

The presence of a carotid bruit increases the likelihood of detecting significant stenosis. Asymptomatic patients with an abdominal aortic aneurysm (AAA) or previous radiotherapy to the neck *who do not meet the criteria of any of the high-risk groups* above do not require screening. It has been shown that the prevalence of carotid stenosis increases proportionally with the number of risk factors present.

------------------------------------------------------------------------

## Treatment

### Carotid Artery Endarterectomy (CEA)

This procedure has been performed since the 1950s, either by plaque endarterectomy and patch angioplasty or primary arterial repair. To prevent arterial restenosis, patch angioplasty has become the standard of arterial closure after plaque removal. The procedure can involve cerebral monitoring including electroencephalography (EEG), transcranial Doppler (TCD) and stump pressure monitoring or be performed awake to directly monitor patient motor response. Endarterectomy and patch repair can be performed under a "clamp and sew" mentality or with an arterial shunt to maintain cerebral perfusion. Risks include cardiopulmonary risk of acute myocardial ischemia, \<3% perioperative risk of neurologic event, neck hematoma or cranial nerve injury of roughly 5-10% affecting the vagus, marginal mandibular, recurrent laryngeal or hypoglossal nerves.

### Carotid Artery Stenting (CAS)

#### Transfemoral Carotid Artery Stenting (TFCAS) with Embolic Protection

Transfemoral stenting requires some type of protection from embolization including a distal internal carotid artery retrievable filter or flow arrest procedure to prevent cerebral embolization during stent placement with or without angioplasty.

#### Transcarotid Artery Revascularization (TCAR)

Treatment of a carotid stenosis that avoids aortic arch manipulation involving direct common carotid artery exposure and sheath placement to allow for transcarotid stent delivery to the internal carotid artery. The common carotid artery sheath is connected to a femoral vein sheath so that the natural arterial pressure gradient reverses flow across the distal internal carotid artery driving blood and possible embolus into the arterial tubing circuit and across a filter before it reenters the venous circulation. As FDA approval for the device was delivered in 2016, the technology is less than 10 years old without robust long-term follow up data. This technique offers a lower perioperative stroke risk than transfemoral stenting, for multiple reasons including lack of transaortic arch manipulation and great vessel cannulation which can result in embolus prior to placement of an internal carotid artery embolic protection device.

### Optimal Medical Management

Understandably, optimal medical management requires full risk evaluation of the individual patient in question including other comorbidities, drug allergies, compliance, etc. We have listed a few broad recommendations to follow that offer general guidance surrounding the dynamic target of optimal medical management for arterial disease.

#### Antiplatelet Therapy

-   ASA offers a 22% risk reduction in major vascular events with no difference in protection based on dosage (81 versus 325 mg).
-   Clopidogrel can be used as an adjunct or alternative to ASA, but the added benefit from dual antiplatelet combination in asymptomatic carotid artery stenosis is unproven.

#### Anticoagulants

-   Only useful for prevention of cardioembolic strokes due to arrhythmia or prosthetic valve.

#### Hypertension Treatment

-   Recommended blood pressure range of \<130/80 with individual antihypertensive regimen based on other comorbidities and patient risk factors.

#### Diabetic Control

-   In accordance with best practice for diabetes management, the patient's hemoglobin A1c should be \<7.0

#### Smoking Cessation

-   Treatments offered include nicotine replacement therapy (NRT), varenicline or bupropion as first line agents.

#### Hyperlipidemia Management

-   Regimen goals of LDL \<100mg/dl, or \<70mg/dl depending on risk profile.

------------------------------------------------------------------------

## Outcomes and Surveillance

### Asymptomatic carotid stenosis

-   The historically touted Asymptomatic Carotid Atherosclerosis Study (ACAS) demonstrated that patients with \>60% carotid stenosis who underwent CEA benefited significantly from stroke risk reduction at 5 years (5.1% for CEA vs. 11% for optimal medical therapy consisting of aspirin alone).
-   More recent studies suggest that with the current optimal medical management, which consists of antiplatelet medication and statin therapy, 5-year stroke risk is highest in patients with \>70% carotid stenosis, and therefore this patient population would benefit from carotid endarterectomy.
-   Patients who are deemed high risk, either due to an anatomic (such as surgically inaccessible bifurcation or restenosis after previous CEA) or physiologic findings (congestive heart failure, severe coronary artery disease, or chronic obstructive pulmonary disease), may be considered for TCAR given the equivocal results of perioperative stroke or death at 1.3%, as compared to CEA.
-   Asymptomatic patients **with significant risk factors** found to have moderate stenoses (50%-79%) should be followed every 6-months to detect disease progression. High risk patients with \<50% stenosis can be followed-up annually.

### Symptomatic carotid stenosis

-   Patients who have \>50% carotid stenosis and have developed symptoms of TIA or stroke were found to benefit from CEA in the pivotal North American Symptomatic Carotid Endarterectomy Trial (NASCET) because of the significant 2-year stroke risk reduction as compared to optimal medical management (15.7% vs. 22.2%.). An even greater stroke risk reduction was seen in patients with \>70% carotid stenosis (9% CEA vs. 26% medical management).
-   Current management of patients with symptomatic \>50% carotid stenosis who are low/standard risk is carotid endarterectomy over transfemoral carotid stenting (TFCAS), as there are no studies to date which have shown benefit of TFCAS.
-   Patients who are deemed high risk, as defined above, may be considered for TCAR over TFCAS due to the significantly lower incidence of in-hospital stroke and death (1.6% vs. 3.1%).
-   Post-operative surveillance (by duplex ultrasound) after open (CEA) or endovascular (TF-CAS) repair of the carotid artery is strongly recommended by the SVS to monitor for signs of restenosis in the repaired artery or atherosclerotic disease progression in the unoperated, contralateral artery. Duplex ultrasound testing is recommended within 30 days of the procedure, then every 6 months for 2 years, then annually.
-   Restenosis \<50% warrants the regular surveillance protocol; 50-99% warrants closer follow-up, confirmation with a CTA, and possible angiographic evaluation; 100% restenosis warrants surveillance and medical treatment of the contralateral carotid artery.
-   It should be noted, there is some debate as to the economic and medical value of continuing post-operative duplex ultrasound surveillance after successful CEA with patch closure when the immediate post-operative duplex was normal or showed minimal disease.

------------------------------------------------------------------------

## Teaching Case

### Scenario

An 81 year old male with a significant smoking history and prior three vessel CABG five years ago, presents with monocular right eye blindness that occurred two days ago. He has no prior ophthalmologic conditions and states that he describes the process of a veil coming down over his right eye with resolution about a minute later with complete return of normal vision at that point. He denies any other symptoms during the event or since, such as motor or sensory deficits, speech, etc. He did not think much of the event but presented after his wife told him to see someone about the event.

### Exam

**HEENT:** No prior neck incisions, good cervical extension.

**Cardiac:** Regular rate and rhythm. Healed sternotomy scar.

**Pulmonary:** Clear to auscultation throughout.

**Abdominal:** Soft and nontender.

**Neurologic:** All cranial nerves 2-12 intact, no lateralizing deficits, 5/5 strength to all extremities.

**Optho:** No visual deficits at 20 feet from eye chart.

### Imaging

**Duplex Ultrasound (Peak Systolic Velocity/End Diastolic Velocity)**

| Location     | Right        | Left        |
|--------------|--------------|-------------|
| Proximal ICA | 540/240 cm/s | 120/45 cm/s |
| Mid ICA      | 230/145 cm/s | 119/37 cm/s |
| Distal ICA   | 240/110 cm/s | 110/23 cm/s |

**Duplex Report:** Based on color flow duplex imaging there is evidence of 80-99% stenosis of the right internal carotid artery segment and \<50% stenosis to the contralateral side.

### Discussion Points

::: callout-note
## N.B. There is no prepared answers for the questions below.

However, we feel this chapter contains all the necessary information to answer the questions. If not, please let us know!
:::

1.  Please explain the pathophysiology of the visual event for this patient? Describe why it can be termed amaurosis fugax. Ensure understanding that amaurosis fugax is the result of carotid plaque embolization to the retina.
2.  Please list the patient's risk factors for carotid disease? What is best medical management to optimize these risk factors?
3.  Is this patient asymptomatic or symptomatic based on the clinical scenario presented?
4.  What next steps should be pursued to offer effective and timely treatment to this patient? Please discuss adjunct imaging such as CTA or MRA to determine anatomic characteristics of the lesions such as ulceration, vessel patency, level (accessible or high lesions), etc.
5.  What surgical managements could be suggested to this patient? Please include a discussion of carotid endarterectomy, transfemoral stenting or TCAR.
6.  What medications should be started in this scenario? Please consider ASA, Plavix, statin medications, etc.
7.  What are some possible relevant complications of surgical intervention, including periprocedural stroke risk?

------------------------------------------------------------------------

## Key Articles

1.  Ricotta JJ, Aburahma A, Ascher E, Eskandari M, Faries P, Lal BK; Society for Vascular Surgery. [Updated Society for Vascular Surgery guidelines for management of extracranial carotid disease.](https://www.jvascsurg.org/article/S0741-5214%2811%2901635-1/fulltext) J Vasc Surg. 2011 Sep;54(3):e1-31.[@Ricotta2011]

2.  AbuRahma AF, Avgerinos EM, Chang RW, Darling RC 3rd, Duncan AA, Forbes TL, Malas MB, Murad MH, Perler BA, Powell RJ, Rockman CB, Zhou W. [SOCIETY FOR VASCULAR SURGERY CLINICAL PRACTICE GUIDELINES FOR MANAGEMENT OF EXTRACRANIAL CEREBROVASCULAR DISEASE.](https://www.jvascsurg.org/article/S0741-5214(21)00893-4/fulltext) J Vasc Surg. 2021 Jun 18. [@aburahma2022]

3.  [Endarterectomy for asymptomatic carotid stenosis.Executive Committee for the Asymptomatic Carotid Atherosclerosis Study.](https://www.urmc.rochester.edu/MediaLibraries/URMCMedia/neurology/documents/ACAS.pdf) JAMA 1995;273(18):1421-8. [@walker1995]

4.  [Beneficial effect of carotid endarterectomy in symptomatic patients with high-grade stenosis. North American Symptomatic Carotid Endarterectomy (NASCET) Trial Collaborators.](https://www.nejm.org/doi/10.1056/NEJM199108153250701?url_ver=Z39.88-2003&rfr_id=ori:rid:crossref.org&rfr_dat=cr_pub%20%200www.ncbi.nlm.nih.gov) N Engl J Med 1991;325(7):445-53.[@benefici1991]

5.  Howard D.P.J., Gaziano L., Rothwell P.M.: [Risk of stroke in relation to degree of asymptomatic carotid stenosis: a population-based cohort study, systematic review, and meta-analysis.](https://www.thelancet.com/journals/laneur/article/PIIS1474-4422(20)30484-1/fulltext) Lancet Neurol 2021; 20: pp. 193-202.[@howard2021]

------------------------------------------------------------------------

## Additional Resources

### Audible Bleeding Content

-   Audible Bleeding Exam Prep: [Cerebrovascular Chapter](https://adam-mdmph.quarto.pub/vascular-surgery-exam-prep/cerebrovascular.html)
-   Audible Bleeding has an episode covering the NASCET trial. Listen to it below and find [additional information here](https://www.audiblebleeding.com/2021/09/29/landmark-papers-nascet/), or find the episode wherever you listen to podcasts. <iframe title="Libsyn Player" style="border: none" src="//html5-player.libsyn.com/embed/episode/id/20601968/height/90/theme/custom/thumbnail/yes/direction/backward/render-playlist/no/custom-color/980c0c/" height="90" width="100%" scrolling="no" allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>

------------------------------------------------------------------------

### Websites

-   TeachMe Surgery: [Carotid Artery Disease](https://teachmesurgery.com/vascular/arterial/carotid-artery-disease/)

------------------------------------------------------------------------

### Serious Games

#### Touch Surgery Simulations.

-   Must download the [Medtronic Touch Surgery mobile application](https://www.medtronic.com/covidien/en-us/products/digital-surgery/simulations.html) to access the modules. Available for Apple and Android mobile devices.
-   [Carotid Endarterectomy](https://lh68.app.link/?$deeplink_path=library/phase?procedure_code=procedure-DAR_CAE&~channel=In-App%20iOS%20Share&~feature=Share%20Phase&~tags=procedure-DAR_CAE)
-   [Carotid Artery Stenting](https://lh68.app.link/?$deeplink_path=library/phase?procedure_code=procedure-CAR_ArtStent&~channel=In-App%20iOS%20Share&~feature=Share%20Phase&~tags=procedure-CAR_ArtStent)

------------------------------------------------------------------------

### Operative Footage

Developed by the Debakey Institute for Cardiovascular Education & Training at Houston Methodist. *YouTube account required as video content is age-restricted.*

#### Carotid Endarterectomy (Short Version)

<iframe width="560" height="315" src="https://www.youtube.com/embed/AWXCpRJAN8M" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>

#### Carotid Endarterectomy (Long Version) Part 1

<iframe width="560" height="315" src="https://www.youtube.com/embed/wZ8PzhwmSXQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

<iframe>

#### Carotid Endarterectomy (Long Version) Part 2

<iframe width="560" height="315" src="https://www.youtube.com/embed/E_wWpRKBy4w" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>

#### Carotid Endarterectomy (Long Version) Part 2

<iframe width="560" height="315" src="https://www.youtube.com/embed/E_wWpRKBy4w" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>

#### Transcarotid Artery Revascularization (TCAR)

<iframe width="560" height="315" src="https://www.youtube.com/embed/kjVyBbDZPnc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>

------------------------------------------------------------------------

<!-- Google tag (gtag.js) -->

```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-WS28VX4802"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-WS28VX4802');
</script>
```
