---
title: "Claudication"
chapter_number: 5
title-block-banner: false
title-block-style: plain
authors: Nakia Sarad, DO, MS, Ezra Schwartz, MD,CM, MS, Marvin Chau, MD, MS, Bernadette Aulivola, MD, FACS, Kelly Kempe, MD, RPVI, FACS, Kaled Diab, MD, and Lindsey Korepta, MD, FACS.
format: html
editor: visual
number-sections: false
bibliography: references.bib
smooth-scroll: true
link-external-newwindow: true
---

#  {#sec-claudication}

::: {.callout-note icon="false"}
## Chapter Learning Objectives

By the end of this chapter, students will:

-   Explain the definition, etiology, and pathophysiology of peripheral arterial disease and its relation to claudication.
-   Identify the risk factors associated with claudication.
-   Recognize the clinical manifestations and symptoms of claudication.
-   Summarize the underlying vascular anatomy and physiology relevant to claudication.
-   Outline the diagnostic approach and tests used to evaluate claudication.
-   Summarize evidence-based outcomes of the management of claudication.
:::

::: {.callout-note icon="false"}
## Key Facts

1.  Peripheral arterial disease (PAD), also known as peripheral vascular disease (PVD), is a condition characterized by atherosclerosis or narrowing of the arteries that supply blood to the extremities.
2.  PAD affects approximately 202 million individuals worldwide.
3.  Major risk factors for PAD include smoking, diabetes, and advanced age.
4.  Claudication is the mildest symptomatic manifestation of peripheral arterial disease.
5.  Claudication is defined as **reproducible** discomfort in a specific muscle group, typically in the lower extremities, that is **induced by exercise and relieved by rest.**
6.  Patients with claudication have an overall 5-year mortality risk of 10-15%.
7.  Approximately 2-3% of claudicants (i.e. patients experiencing claudication) will develop limb-threatening ischemia.
8.  Claudication is managed conservatively with lifestyle modifications including exercise regimen, dietary changes, smoking cessation, and medical optimization to control hypertension, hyperlipidemia, and or diabetes.
:::

::: callout-tip
## How We Suggest Using the Pre/Post Questions

The pre/post questions are listed below. They are all multiple choice questions with a single right answer. To best guide your learning, we have hidden the answers in a collapsible menu. Before reading the chapter, we suggest giving the questions a try, noting your answers on a notepad. After reading the chapter, return to the questions, re-evaluate your answers, and then open the collapsible menu to read the correct answer and discussion. Do not fret if you have difficulty answering the questions before reading the chapter! By the end of the chapter, we are certain you will have covered the knowledge necessary to answer the questions. There will be a teaching case at the end of the chapter. This is another opportunity to exercise your new knowledge!
:::

## Pre/Post Questions

### Case Based Questions

1.  A 70-year-old male, who has a history of heavy smoking (100 pack years), presents to the clinic for claudication-like symptoms. *What level of infrainguinal arterial occlusive disease is he most at risk for developing based on this history?*

<!-- -->

A.  Superficial femoral artery disease.

B.  Deep femoral artery disease.

C.  Anterior tibial artery disease.

D.  Popliteal artery disease.

E.  Posterior tibial artery disease.

::: {.callout-note icon="false" collapse="true"}
## Answer

**A. Superficial femoral artery disease.**

Discussion: The prevalence of peripheral artery disease in the general population is between 3-10%, and 15-20% in those over the age of 70. Risk factors for peripheral arterial disease (PAD) include age, male gender, hypertension, diabetes, smoking, dyslipidemia, family history and homocysteinemia. Heavy smokers have a propensity to develop superficial femoral artery disease (A). Patients with a history of diabetes have a tendency to develop infrapopliteal disease (C, E). Patients of nonwhite ethnicity and those with a history of chronic renal insufficiency are also at increased risk.
:::

2.  A 67-year-old female is being evaluated in the outpatient clinic for lower extremity pain associated with walking. Using a manual blood pressure cuff and hand-held Doppler, the following measurements are obtained:

| Artery                | Pressure (mm Hg) |      |
|-----------------------|------------------|------|
|                       | Right            | Left |
| Brachial              | 150              | 120  |
| Dorsalis pedis (DP)   | 165              | 120  |
| Posterior tibial (PT) | 150              | 108  |

*What are the ankle-brachial indices (ABIs) of her lower extremities?*

A.  Right ABI 1.1; left ABI 0.8

B.  Right ABI 1.0; left ABI 1.0

C.  Right ABI 1.2; left ABI 0.9

D.  Right ABI 1.4; left ABI 1.0

E.  Right ABI 1.1; left ABI 0.7

::: {.callout-note icon="false" collapse="true"}
## Answer

**A. Right ABI 1.1; left ABI 0.8**

Discussion: Performing an ankle-brachial index (ABI) requires an appropriately sized manual blood pressure cuff and a hand-held, continuous-wave Doppler probe. The patient should be in the supine position and allowed to rest before the examination begins. The blood pressure cuff is placed above the ankle. The Doppler probe is used to locate the dorsalis pedis (DP) or posterior tibial (PT) pulse. The pressure cuff is inflated until the Doppler signal is obliterated, and then the cuff is then slowly released. The pressure at which the Doppler signal returns is the ankle pressure. The same process is repeated for both legs (DP and PT signals) and both arms. The arm pressure must be measured with the Doppler probe and the manual blood pressure cuff. To calculate an ABI, the higher ankle pressure (DP or PT) is divided by the highest arm pressure (left or right). Note that the higher arm pressure is used to calculate the ABI for both legs. For this specific case, the highest arm pressure is 150. To calculate on the right, 165/150=1.1, on the left 120/150=0.8. A normal ABI is 0.9 to 1.2. Patients with claudication usually have an ABI ranging from 0.5 to 0.9, and those with ischemic rest pain or tissue loss usually have an ABI less than 0.5. *Sabiston Textbook of Surgery: The Biological Basis of Modern Surgical Practice, 20th ed. Ch. 62: Peripheral Arterial Disease.* *Norgren L, Hiatt WR, Dormandy JA, Nehler MR, Harris KA, Fowkes FGR. Inter-society consensus for the management of peripheral arterial disease (TASC II). J Vasc Surg. 2007;45:S5-S67.*
:::

3.  A 70-year-old male with poorly controlled diabetes and no smoking history presents to the clinic for an ischemic toe ulcer. *What level of infrainguinal arterial occlusive disease is he most at risk for developing based on this history?*

<!-- -->

A.  Superficial femoral artery disease

B.  Deep femoral artery disease

C.  Iliac artery disease

D.  Aortic disease

E.  Tibial artery disease

::: {.callout-note icon="false" collapse="true"}
## Answer

**E. Tibial artery disease.**

Discussion: Risk factors for peripheral arterial disease include age, male gender, hypertension, diabetes, smoking, dyslipidemia, family history, and homocysteinemia. Individuals who are heavy smokers tend to develop superficial femoral artery disease, whereas those with diabetes and renal failure tend to develop infrapopliteal disease. Of the answers listed, only the tibial artery is infrapopliteal.
:::

**The following prompt will be used for questions 4, 5, and 6.**

A 65-year old male with a history of hypertension, hyperlipidemia, and tobacco abuse presents to the vascular surgery clinic with complaints of pain in his legs. Patient states that the pain is crampy in quality, mostly in his calf muscles, it starts after he walks 4 blocks, and is worse on the right as compared to the left. He notices that when he stops walking, the pain resolves. This pain is keeping him from being able to participate in social events and spend quality time with his family.

4.  *What is the name of the symptom the patient is experiencing?*

<!-- -->

A.  Neuropathy

B.  Claudication

C.  Ischemic rest pain

D.  Bilateral sciatica

E.  Normal symptoms

::: {.callout-note icon="false" collapse="true"}
## Answer

**B. Claudication**

Discussion: Claudication is defined as reproducible pain or cramping of the lower extremities that occurs with ambulation and significantly improves or resolves at rest. Claudication can occur in any muscle group distal to the area of arterial stenosis and/or occlusion. As such, the calf muscles are the most common anatomic location to experience pain as they are distal in the lower extremity. As the patient does not report pain at rest, they do not have ischemic rest pain. Neuropathic pain or bilateral sciatica and claudication can be confused. Neuropathic pain is shocking in quality whereas claudication is describes as a cramp-type pain. Furthermore, claudication is absent at rest, triggered by exercise, and relieved by a return to rest. This pattern helps distinguish claudication from neuropathic pain. This patient also does not have normal pathology, as one should not have pain on ambulation and needs to be further evaluated.
:::

5.  *What would be the first step in confirming the diagnosis for this patient?*

<!-- -->

A.  CT Angiography (CTA)

B.  Doppler probe

C.  Duplex Ultrasound

D.  Angiogram

E.  Ankle-Brachial Index and Pulse Volume Recording (ABI/PVR)

::: {.callout-note icon="false" collapse="true"}
## Answer

**E. ABI/PVR**

Discussion: Ankle Brachial Index (ABI) is a non-invasive method that measures the ratio of blood pressure in the lower legs to the blood pressure in the arms. Abnormal ABIs have been shown to have high specificity with identifying PAD. Patients who have claudication usually have ABI ranges from 0.5 to 0.9. Pulse volume recordings (PVR) use pressure cuffs to record the shape of a pulse. The type of waveform provides important information about the characteristics of blood flow. Waveforms can be used to diagnose and monitor arterial diseases, assess the severity of stenosis, and determine the effectiveness of treatment interventions. This patient likely has claudication based on the history and symptoms. The first non-invasive testing to confirm the diagnosis would be ABI/PVR. While a CTA would provide helful information with regards to arterial anatomy and the extend of calcification, it cannot provide the physiologic information that one would obtains an ABI/PVR. Furthermore, CTA requires contrast and radiation exposure. While used in measuring an ABI, a Doppler probe is not nearly as sensitive in identifying PAD and does not provide data helpful in creating a management plan. A Duplex Ultrasound would provide physiologic information as to the burden of disease. However, it is highly operator dependent and requires more resources. It may be considered as a second line investigation. While an angiogram is the gold-standard, it is an invasive technique that requires the use of contrast. As such, it is not a first line investigation.
:::

6.  *What would be the first step in treating this patient's symptoms?*

<!-- -->

A.  Angiogram to identify targets for open surgical bypass.

B.  Angiogram with angioplasty/stent of any occluded vessels.

C.  Prescribe Cilostazol.

D.  Ensure medication optimization for his hypertension and hyperlipidemia, smoking cessation counseling, and exercise regimen.

E.  No treatments at this time, continue to monitor and come back to clinic in 3 months.

::: {.callout-note icon="false" collapse="true"}
## Answer

**D. Ensure medication optimization for his hypertension and hyperlipidemia, smoking cessation counseling, and exercise regimen.**

Discussion: The mainstay of treatment for claudication is conservative management, including medical optimization and lifestyle modification. The patient has hypertension and hyperlipidemia. He should be on appropriate antihypertensive to control the blood pressure. With regard to medical optimization, it is recommended that patients start on antiplatelet therapy (Aspirin 81 mg daily) and a high dose statin. Lifestyle modifications include smoking cessation, exercise training to develop collateral vessels, and diet modification to lower cholesterol intake. An appropriate exercise regimen is defined by at least 30 minutes of supervised ambulation/exercise at least 3 times per week. Patients should be followed closely with yearly ABIs by both Primary Care Physicians (PCPs) and Vascular Surgeons for progression of disease. While an angiogram allows for simultaneous diagnosis and treatment of PAD, it is an invasive technique that requires the use of contrast. Angiogram may be considered if conservative management fails. Cilostazol is an antiplatelet that has been shown to have beneficial effects for patients wtih intermittent claudication, however, it is not a first-line medication. Lastly, while follow-up is important in the management of PAD, conservative management should be initiated as soon as the diagnosis of PAD is made.
:::

------------------------------------------------------------------------

## Introduction

::: callout-tip
The term peripheral arterial disease (PAD) is often used interchangeably with peripheral vascular disease (PVD) when referring to arterial blockages.
:::

**Claudication is defined as cramping, pain, and/or discomfort in the hip, thigh, or calves that occurs with ambulation/exercise, improves shortly after cessation of activity, and recurs after a predictable amount of ambulation/exercise.**

Claudication is a symptom of peripheral arterial disease (PAD). Therefore, it is important to first understand PAD before addressing claudication. PAD is a chronic condition of arterial insufficiency due to the build-up of atherosclerotic plaque (or fatty deposits) in the arteries. PAD affects 8.5 million adults in the U.S. and 202 million adults worldwide, with approximately 15% of the population aged greater than 70 years old suffering from PAD. Risk factors for PAD include increasing age, hypertension, hyperlipidemia, renal disease, diabetes, and smoking. The risk factors for claudication are the same risk factors described for PAD, including: advanced age, race (non-hispanic blacks), male gender, smoking, diabetes mellitus, dyslipidemia, hypertension, renal insufficiency, and elevated homocysteine levels (hypercoagulable state). PAD has various distributions in the body including one or a combination of aortoiliac, femoral, and infrapopliteal disease. PAD severity falls along a spectrum. Some patients may be completely asymptomatic while others have nonhealing, chronically infected wounds requiring later limb amputation. Vascular claudication is the mildest symptomatic manifestation of the PAD spectrum.

------------------------------------------------------------------------

## Etiology

Prior to understanding the etiology of claudication and peripheral arterial disease. It is important to review the anatomy of the arterial blood flow of the lower extremity.

### Anatomy

The arterial anatomy of the lower extremity is a complex network of arteries that supply blood to the legs and feet. Please find an [image here](https://radiology.wales/wp-content/uploads/2018/10/leg-artery-anatomy.jpg) and a description below of the major arteries from the common femoral artery down to the tibioperoneal trunk, anterior tibial, and dorsalis pedis arteries:

-   **Common Femoral Artery (CFA):** The common femoral artery is a large, thick-walled artery located in the groin. It is a continuation of the external iliac artery and bifurcates into the deep femoral artery (profunda femoris) and the superficial femoral artery.
-   **Superficial Femoral Artery (SFA):** The superficial femoral artery is the largest branch of the common femoral artery. It descends along the anterior and medial aspect of the thigh and enters the adductor canal. As it descends, it eventually becomes the popliteal artery at the level of the knee joint.
-   **Profunda Femoris (Deep Femoral) Artery (PFA):** The profunda femoris artery, also known as the deep femoral artery, is a significant branch of the common femoral artery. It typically arises about 1 to 2 cm below the inguinal ligament. The profunda femoris artery primarily supplies the muscles of the posterior and deep thigh, including the quadriceps muscles. It is also an important collateral pathway for blood flow in cases of arterial obstruction or occlusion in the lower extremity distal to the SFA/PFA bifurcation.
-   **Popliteal Artery:** The popliteal artery is located behind the knee joint and is a continuation of the superficial femoral artery. It provides blood supply to the muscles and structures in the popliteal fossa and gives rise to several branches, including the anterior tibial, posterior tibial, and peroneal arteries.
-   **Anterior Tibial Artery (AT):** The anterior tibial artery is the first branch off of the popliteal artery. It is NOT part of the tibioperoneal trunk (only includes the PT and peroneal arteries. The AT passes from behind the knee through the interosseous membrane of the leg and descends through the anterior compartment of the leg. It can be visualized as the most lateral tibial vessel during lower extremity angiogram run-offs. The AT runs along the front of the tibia and crosses the ankle joint to become the dorsalis pedis artery, supplying blood to the dorsum (top) of the foot.
-   **Posterior Tibial Artery (PT):** The posterior tibial artery is another branch of the popliteal artery. Once the AT tibial branches from the popliteal, the remaining vessel is termed the tibeoperoneal trunk. This trunk splits to give off the posterior tibial artery (PT) and the peroneal artery. The PT descends posteriorly in the leg and passes behind the medial malleolus (the bony prominence on the inner side of the ankle). It can be palpated on the medial aspect of the foot behind the medial malleolus. It continues into the sole of the foot and forms the plantar arch, contributing to the arterial supply of the sole of the foot and toes.
-   **Peroneal Artery:** The peroneal artery, also known as the fibular artery, is the third major branch of the popliteal artery. As mentioned, it originated from tibioperoneal trunk along with the PT. The peroneal artery runs along the lateral side of the leg and supplies the lateral compartment muscles. In the ankle region, it anastomoses with the branches of the posterior tibial artery, providing collateral circulation.
-   **Dorsalis Pedis Artery (DP):** The dorsalis pedis artery is a continuation of the anterior tibial artery. It extends along the anterior aspect of the ankle and runs atop the dorsum (top) of the foot. It can be palpated on the dorsum of the foot just lateral to the tender of extensor hallucis longus. It plays a crucial role in supplying blood to the dorsal surface of the foot and the toes. The presence and palpability of the dorsalis pedis pulse are often evaluated as part of a clinical assessment to determine arterial perfusion in the foot.

In summary, the common femoral artery is the arterial origin of the leg. It gives rise to the superficial femoral artery, and subsequently, the popliteal artery. The popliteal artery then divides into the anterior tibial, posterior tibial, and peroneal arteries, each supplying specific regions of the leg and foot. Understanding this anatomy is crucial for diagnosing and treating arterial diseases and vascular disorders in the lower extremities.

::: callout-tip
For a short, comprehensive, although advanced video lecture reviewing normal and diseased lower limb arterial anatomy, please see the video below.

<iframe width="560" height="315" src="https://www.youtube.com/embed/SLKJZe4w0iI?si=3Hn4gCXFT1SLYCNo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen>

</iframe>
:::

::: callout-note
[Here](https://musculoskeletalkey.com/8-vascular-anatomy-of-the-lower-extremity-a-practical-guide-to-vascular-territories-perforators-and-selection-of-recipient-vessels/) is a review of the lower extremity vascular anatomy and here are two sample diagnostic angiograms of these vessels ([Sample 1](https://ars.els-cdn.com/content/image/1-s2.0-S2211568422001231-gr1.jpg), [Sample 2](https://ars.els-cdn.com/content/image/1-s2.0-S2211568422001231-gr2.jpg)).
:::

### Process of Atherosclerosis

As previously mentioned, atherosclerosis is a fundamental process that underlies the development of peripheral vascular disease in the lower extremities. The pathological process is precisely the same as with carotid disease leading to increasing stroke risk and coronary artery disease leading to increased risk of cardiac events.

Atherosclerosis is a progressive, inflammatory condition characterized by the accumulation of fatty deposits, cholesterol, inflammatory cells, and fibrous tissue within the inner layers of arteries, forming plaques. The process typically begins with damage or dysfunction of the endothelial lining of the arterial walls. This can be caused by risk factors such as hypertension, smoking, or high cholesterol levels. In response to endothelial injury, low-density lipoproteins (LDL) or "bad" cholesterol molecules penetrate the arterial wall and become oxidized. These oxidized lipids trigger an inflammatory response. The body's immune system responds to the inflammatory signals by sending white blood cells (macrophages) to the site. These cells engulf the oxidized lipids and form foam cells within the arterial wall. The inflammation leads to the proliferation of smooth muscle cells. Over time, the combination of lipids, immune cells, and smooth muscle cell proliferation results in the formation of atherosclerotic plaques. These plaques narrow the arterial lumen, restricting blood flow. The build-up of plaques can lead to stiffening and loss of elasticity in the arterial walls, further diminishing the artery's ability to dilate and maintain adequate blood flow.

As the arterial narrowing progresses, blood flow to the downstream tissues (e.g., muscles, nerves, and skin in the lower extremities) becomes compromised. This can lead to ischemia, which manifests as claudication -- a symptom characterized by intermittent pain, cramping, and fatigue in the muscles during physical activity that resolves once at rest. In severe cases, atherosclerosis can lead to critical limb threatening ischemia (CLTI), a condition marked by severe arterial blockages and tissue damage. CLTI can result in non-healing ulcers, gangrene, and, in the absence of intervention, limb amputation. Atherosclerotic plaques are also prone to rupture or ulceration, exposing their contents to the bloodstream. This can lead to the formation of blood clots (thrombosis) or embolization of plaque fragments to smaller arteries, causing acute blockages that may lead to acute limb ischemia (ALI). CLTI and ALI will be discussed in more detail in the subsequent PAD chapters.

::: callout-note
The following lipid levels are considered to be "good" in healthy people:

-   Total cholesterol: Levels below 200 mg/dL (5.2 mmol/L)
-   LDL cholesterol: Levels below 130 mg/dL (3.4 mmol/L)
-   HDL cholesterol: Levels above 40 mg/dL (1 mmol/L) in men and above 50 mg/dL (1.3 mmol/L) in women

[The American Diabetes Association (ADA) standards of care for diabetes](https://diabetesjournals.org/care/article/46/4/898/148368/Erratum-10-Cardiovascular-disease-and-risk) recommend that statin therapy should be initiated in individuals with diabetes and other atherosclerotic cardiovascular disease (ASCVD) risk factors.

Please see the [ASCVD risk calculator algorithm](https://www.mdcalc.com/calc/3400/ascvd-atherosclerotic-cardiovascular-disease-risk-algorithm-including-known-ascvd-aha-acc):

-   For patients ages 40 years and older with diabetes: Use moderate-dose statin therapy.
-   For patients ages 40 to 75 with diabetes and a higher cardiovascular risk (including those with one or more ASCVD risk factors): Use high-intensity statin therapy to reduce LDL cholesterol by ≥50% of baseline and target an LDL cholesterol goal of \<70 mg/dL.
-   For patients with diabetes who have already had an ASCVD event: High-intensity statin therapy is recommended to target an LDL cholesterol reduction of ≥50% from baseline and an LDL cholesterol goal of \<55 mg/dL.
:::

### PAD Risk Factors

All these risk factors increase rates of atherosclerosis and start to limit the blood flow to the lower extremities, attributing to claudication.

-   **Smoking:** Smoking is a well-established major risk factor for PAD. It contributes to PAD through multiple mechanisms, including endothelial dysfunction, oxidative stress, inflammation, and platelet activation. The nicotine in tobacco constricts blood vessels and promotes the formation of atherosclerotic plaques. Moreover, smoking cessation is the most effective intervention in reducing the progression of PAD.

-   **Diabetes Mellitus**: Diabetes is closely associated with PAD due to hyperglycemia-induced endothelial dysfunction and microvascular damage. It accelerates atherosclerosis by promoting lipid abnormalities, systemic inflammation, and the development of neuropathy, which can mask or delay the recognition of PAD symptoms.

-   **Hypertension:** Hypertension is a major contributor to PAD. Elevated blood pressure damages arterial walls, rendering them more susceptible to atherosclerosis. Hypertension also increases the risk of thrombosis and clot formation, further compromising arterial perfusion.

-   **Hyperlipidemia:** High levels of low-density lipoprotein (LDL) cholesterol are a known risk factor for PAD. Elevated LDL cholesterol leads to the accumulation of lipid deposits in arterial walls, initiating the atherosclerotic process. Dyslipidemia management, particularly the reduction of LDL cholesterol, is essential in PAD prevention and management.

-   **Age:** Age is an independent risk factor for PAD. As individuals age, atherosclerotic processes accumulate, contributing to a higher likelihood of PAD development.

-   **Family History:** Genetic predisposition can influence an individual's susceptibility to PAD. A family history of vascular disease, particularly atherosclerosis, can confer a higher risk.

-   **Obesity:** Obesity is one of the multifactorial contributors to the formation of PAD. Excess adipose tissue is associated with insulin resistance, chronic inflammation, and altered lipid profiles. These factors contribute to atherosclerosis and PAD development.

-   **Physical Innactivity:** A sedentary lifestyle not only contributes to obesity but also reduces overall vascular health. Regular physical activity, conversely, is associated with better arterial function and can mitigate PAD risk.

-   **Diet:** A diet rich in saturated and trans fats, along with a low intake of fruits and vegetables, promotes the development of atherosclerosis. In contrast, diets emphasizing heart-healthy components, such as whole grains, fruits, vegetables, and lean protein, are associated with reduced PAD risk.

-   **Metabolic Syndrome:** Metabolic syndrome, which encompasses a cluster of conditions such as obesity, hypertension, hyperglycemia, and dyslipidemia, is a potent risk factor for PAD. The interplay of these factors significantly increases the risk of atherosclerosis and impaired arterial perfusion.

-   **Gender and Menopause:** Men generally exhibit a higher prevalence of PAD, although the risk in women increases post-menopause. Reduced estrogen levels post-menopause contribute to endothelial dysfunction and alterations in lipid profiles, increasing susceptibility to PAD.

-   **Race and Ethnicity:** Certain racial and ethnic groups, such as African Americans, are more prone to developing PAD. Genetic and environmental factors may contribute to these disparities.

-   **Chronic Kidney Disease (CKD):** Reduced kidney function is associated with PAD, partly due to endothelial dysfunction and systemic inflammation. CKD patients are at increased risk of atherosclerosis, uncontrolled hypertension, thrombotic complications, and progressive PAD.

### Vessel Collaterization

Patients with peripheral arterial disease (PAD) often develop collateralization of blood vessels as a compensatory mechanism to improve perfusion to tissues affected by reduced blood flow. These new blood vessels, or collaterals, bypass or supplement the obstructed arteries and combat oxygen starvation of the tissues through "collateral circulation." The main drivers for the development of collateral vessels in PAD are as follows:

-   **Ischemia and Hypoxia:** In PAD, atherosclerosis narrows and sometimes occludes the arteries that supply blood to the limbs. The resulting reduced blood flow causes tissue ischemia (insufficient blood supply) and hypoxia (insufficient oxygen supply) to the tissues distal to the narrowing or occlusion. To combat this, the body initiates a response to create alternate pathways for blood flow.

-   **Hypoxia-Inducible Factors (HIFs):** When cells are deprived of oxygen (as in the case of PAD), they activate hypoxia-inducible factors (HIFs). HIFs are transcription factors such as vascular endothelial growth factor (VEGF) and fibroblast growth factor (FGF). These factors promote the expression of genes involved in angiogenesis (the formation of new blood vessels) and arteriogenesis (the remodeling and enlargement of existing collateral vessels) through the stimulation of endothelial cells. Endothelial cells line blood vessels and play a central role in angiogenesis. They respond to these growth factors enabling endothelial cell proliferation and migration, which are essential for the formation of new capillaries in the direction of the hypoxic tissue.

-   **Vasodilation:** When blood vessels are exposed to reduced oxygen levels, they often dilate in an attempt to increase blood flow. This vasodilation can help mobilize and enhance the development of collateral vessels.

-   **Angiogenesis and Arteriogenesis:** Angiogenesis involves the formation of small capillaries, while arteriogenesis involves the enlargement and maturation of existing collateral vessels into larger arteries. These processes are driven by growth factors and signaling molecules like vascular endothelial growth factor (VEGF), fibroblast growth factor (FGF), and various cytokines. As stated previously, they promote the proliferation and migration of endothelial cells and smooth muscle cells, leading to the formation of new blood vessels and the remodeling of existing ones.

-   **Shear Stress:** As blood flows through collateral vessels, it exerts shear stress on the vessel walls. Shear stress is a mechanical force that can trigger the release of molecules like nitric oxide, which further stimulates vessel growth and remodeling.

-   **Physical Activity:** Exercise and physical activity can also stimulate collateralization by increasing shear stress on the vessel walls, enhancing collateral vessel growth. Furthermore, physical activity increases oxygen demand of the active tissues creating a relative hypoxic environment, leading to collateralization/angiogenesis/arteriogenesis as described above. This is why dedicated exercise is an important aspect of treatment for claudication.

The development of collateral circulation in PAD is a gradual process that occurs over time in response to the chronic reduction in blood flow. While collateralization can help improve perfusion to some extent, it may not fully compensate for the lost function of the original, diseased arteries. In advanced stages of PAD, when the arterial obstruction is severe, collateralization may become insufficient, leading to continued symptoms of intermittent claudication, pain, and impaired wound healing.

### Anatomic Distribution of PAD

The distribution of disease in PAD varies among different risk groups such as smokers and diabetics. *Smokers tend to develop PAD predominantly in the infrainguinal arteries (CFA, SFA, PFA, popliteal artery), while diabetics tend to have higher infrapopliteal disease patterns (AT, TP, peroneal, DP).* [@conte2019]

Smoking is a major risk factor for atherosclerosis, which is the primary underlying cause of PAD. Atherosclerosis tends to affect larger and proximal arteries, including the femoral and popliteal arteries, in smokers. The buildup of atherosclerotic plaques narrows these arteries, reducing blood flow to the lower extremities and causing symptoms like claudication.

Diabetes is associated with a specific type of arterial disease known as diabetic vasculopathy or microangiopathy. This condition leads to changes in the smaller blood vessels, including the tibial arteries and peroneal artery. The tibial arteries play a critical role in supplying blood to the feet, making them susceptible to diabetic vascular complications. Therefore, the microvascular changes associated with diabetes result in a distal distribution of arterial disease (i.e. toes and feet first).

------------------------------------------------------------------------

## Diagnostics and Imaging

Measurement of the ankle-brachial index (ABI) is the primary method for establishing the diagnosis of PAD, however, a proper physical exam helps confirm the diagnosis of claudication.

### Peripheral Pulse Exam

In terms of physical exam, claudicants may exhibit signs of muscle wasting with thin, dry, and hairless skin, or even ulceration. These are all signs that blood flow is reduced to the point that there are not enough nutrients to feed these tissues. If ulceration or non-healing wounds are present, the patient likely has advanced peripheral arterial disease (i.e. critical limb ischemia). In addition, a lower extremity motor/sensory exam and peripheral pulse assessment is key.

::: callout-note
Pulse exams study the presence, strength, and character of arterial blood flow and are graded on a scale from 0 to 4+. 0: non-palpable pulse 1+: diminished pulse 2+: normal pulse 3+: prominent pulse or aneurysmal. 4+: bounding pulse or aneurysmal.
:::

Lower extremity peripheral pulse exams evaluate the dorsalis pedis (DP) and posterior tibial (PT) pulses using manual palpation. Patients with claudication may have pulse exams ranging from non-palpable to normal pulse. If patients have non-palpable pulses, then a continuous-wave Doppler probe can be used to assess blood flow.

### Ankle Brachial Index (ABI)

Ankle Brachial Index (ABI) is a non-invasive method that measures the ratio of blood pressure in the lower legs to the blood pressure in the arms. Performing an ABI requires an appropriately sized manual blood pressure cuff and a hand-held, continuous-wave Doppler probe. The patient should be in the supine position and allowed to rest before the examination begins. The blood pressure cuff is placed above the ankle. The Doppler probe is used to locate the dorsalis pedis (DP) or posterior tibial (PT) pulse, the cuff is inflated until the Doppler signal is obliterated, and then the cuff is then slowly released; the pressure at which the Doppler signal returns is the ankle pressure. The same process is repeated for both legs (DP and PT signals) and both arms. The arm pressure must be conducted with the manual blood pressure cuff that is placed above the target vessel and the Doppler probe that is placed below the cuff to evaluate blood flow. To calculate the ABI, the higher ankle pressure (DP or PT) is divided by the highest arm pressure (left or right).

ABI result of \<0.9 has shown to have high sensitivity and specificity with identifying PAD. Patients with claudication usually have an ABI ranging from 0.5 to 0.9, and those with ischemic rest pain or tissue loss usually have an ABI less than 0.5.

::: callout-note
Below are the parameters used to diagnose PAD using ABI values.

1\. ABI of \>1.2: Calcification of arteries, non-compressible. Seen in diabetic patients.

2\. ABI of 0.9 -- 1.2: Normal

3\. ABI of \<0.9: Suggests arterial stenosis. [@khan2008]

\- ABI 0.7-0.9 = mild PAD

\- ABI 0.4-0.7 = moderate PAD

\- ABI \<0.4 = severe PAD

ABI 0.5 - 0.9: often causes claudication

ABI \<0.5: often causes ischemic rest pain/tissue loss
:::

Below, we will review how to calculate the ABI for the right and left lower extremity using the following values:

| Artery                | Pressure (mm Hg) |      |
|-----------------------|------------------|------|
|                       | Right            | Left |
| Brachial              | 150              | 130  |
| Dorsalis pedis (DP)   | 145              | 120  |
| Posterior tibial (PT) | 150              | 110  |

For both right and left lower extremities, the highest brachial pressure is 150 and will be used for comparison for the ankle/brachial index.

On the right lower extremity, using the DP systolic pressure the ABI is 145/150 = 0.97 and using the PT systolic pressure the ABI = 150/150 = 1.0. So the Right ABI is 1.0, because we choose the highest of the two ankle pressures for the final value of the ABI.

On the left lower extremity, using the DP systolic pressure the ABI is 120/150 = 0.8 and using the PT systolic pressure the ABI = 110/150 = 0.73. So the Left ABI is 0.8, because we choose the highest of the two ankle pressures for the final value of the ABI.

For this above example, R ABI = 1.0 and L ABI = 0.8. So this patient may have some peripheral vascular disease present in his left lower extremity as his ABI is less than 0.9.

::: callout-tip
[Here](https://www.youtube.com/watch?v=KnJDrmfIXGw) is a video demonstrating how to obtain and calculate an ABI.
:::

### Pulse volume recordings (PVR)

Pulse volume recordings (PVR) use pressure cuffs to record the shape of a pulse. The type of waveform provides important information about the characteristics of blood flow. These waveforms can be categorized as triphasic, bisphasic, or monophasic. Clinicians use these waveform patterns to diagnose and monitor arterial diseases, assess the severity of stenosis, and determine the effectiveness of treatment interventions.

Pulse volume recordings (PVR) use pressure cuffs to record the shape of a pulse. The type of waveform provides important information about the characteristics of blood flow. These waveforms can be categorized as triphasic, bisphasic, or monophasic. Clinicians use these waveform patterns to diagnose and monitor arterial diseases, assess the severity of stenosis, and determine the effectiveness of treatment interventions.

-   **Triphasic Waveform:**

-   A triphasic waveform consists of three phases: forward flow during systole, a brief reverse flow during early diastole, and a second forward flow component during late diastole.

-   *Clinical Significance:* Triphasic waveforms are typically found in healthy, unobstructed arteries. They represent normal arterial blood flow. These waveforms are seen in arteries serving well-perfused tissues where resistance is low, and blood flow is unimpeded. Triphasic waveforms are commonly observed in the larger arteries of the extremities, such as the femoral and brachial arteries.

-   **Biphasic Waveform:**

-   A biphasic waveform displays two phases: an initial forward flow during systole (when the heart contracts and ejects blood) followed by brief reverse or "reflected" flow during early diastole.

-   *Clinical Significance:* Biphasic waveforms are often associated with moderate arterial stenosis. The reverse flow component indicates some degree of obstruction. They can be observed in patients with early-stage PAD or moderate occlusions. Biphasic waveforms suggest that some blood is able to flow past the obstruction during systole but encounters resistance during diastole.

-   **Monophasic Waveform:**

-   A monophasic waveform consists of a single, continuous flow signal that moves in one direction. It typically lacks a distinct reverse or "reflected" flow signal.

-   *Clinical Significance:* Monophasic waveforms are often seen in arteries downstream from significant stenosis or occlusion. In these cases, there is limited or no backflow during diastole (the relaxation phase of the cardiac cycle). They are commonly found in patients with advanced peripheral arterial disease (PAD) or severe arterial blockages, suggestive of reduced perfusion to the tissues served by the artery.

-   **Flat-line:**

-   A flat waveform (i.e. no wave) does not necessarily indicate no blood flow. A flat wave form simply reflects the lack of pulsatile blood flow.

### Doppler

Doppler devices (handheld or otherwise) provide similar information to PVR studies. Instead of providing a visual representation of pulsatile flow, Doppler signals (sounds) are an auditory representation of flow. A triphasic pulse generates a triphasic signal (repeated sound), a biphasic pule a biphasic signal, and a monophasic pulse a monophasic signal.

::: callout-tip
[Here](https://www.youtube.com/watch?v=C4Utl1wkoio) is a video that demonstrates how to use a doppler probe and the signals associated with each waveform type. You can learn more about doppler probes and waveforms [here](https://www.portailvasculaire.fr/sites/default/files/docs/interpretation_of_peripheral_arterial_and_venous_doppler_waveforms-_a_consensus_statement_vm2020.pdf).
:::

### Duplex Ultrasonography

Duplex ultrasonography (US) is another non-invasive imaging modality that can evaluate a patient's blood flow by measuring the speed at which blood travels through the vessel. In this way, a patient's hemodynamics can be assessed by identifying the location and degree of stenosis. Other imaging modalities such as a CT angiogram or invasive angiograms can also evaluate blood flow to the lower extremities.

A hematologic evaluation (including CBC, fasting blood glucose, creatinine, fasting lipid profile and urinalysis) is recommended in order to identify any associated comorbidities such as diabetes, hyperlipidemia, and chronic kidney disease that may also need to be addressed.

If patients have normal ABIs and pulse exams, it is important to consider other differentials of bilateral lower extremity pain include hematologic or neurogenic claudication (pain caused by lumbosacral nerve root impingement). Neurogenic claudication is positional, often worse when walking downhill and and relieved by leaning forward (i.e. leaning on a walker).

------------------------------------------------------------------------

## Treatment

The mainstay of treatment for claudication is conservative management, including medical optimization and lifestyle modification. With regard to medical optimization, it is recommended that patients start on antiplatelet therapy (Aspirin 81 mg daily) and a high dose statin. Patients without a prior history of congestive heart failure can also start on cilostozal (Pletal) to help with pain management. Patients with prior history of hypertension and diabetes should also be on appropriate antihypertensives to control their blood pressure and diabetes medications to control their blood sugar levels. Lifestyle modifications include smoking cessation, exercise training to develop collateral vessels, and diet modification to lower cholesterol intake. An appropriate exercise regimen is defined by at least 30 minutes of supervised ambulation/exercise at least 3 times per week. Patients should be followed closely with yearly ABIs by both Primary Care Physicians (PCPs) and Vascular Surgeons for progression of disease.

Below is an outline of appropriate treatment options for claudication:

### Supervised Exercise Regimen

Goal of at least 30 minutes of supervised walking exercise (at least 3 times a week)

### Optimization of cardiovascular risk factors:

**Hypertension** - Use of antihypertensive medications - Identify any underlying etiology of hypertension (ie renal artery stenosis, stressors)

**Hyperlipidemia** - Control of cholesterol levels - Diet/exercise modification - Use of medications: i.e. statins, anti-platelet agents

**Diabetes mellitus** - Control of blood glucose levels - Diet/exercise modification - Medications (i.e. antihyperglycemics)

**Smoking Cessation**

### Pain Management

**Anti-inflammatories** (ie acetaminophen, ibuprofen)

**Cilostazol**

------------------------------------------------------------------------

## Outcomes

When treated appropriately, most patients with claudication will not experience limb loss. Only 1-3% of claudicants develop critical limb ischemia and the complications associated with more severe PAD. While the majority of patients (70-80%) have stable claudication symptoms, approximately 20-30% of patients experience a worsening of their claudication. In terms of overall morbidity and mortality, patients with claudication have worse overall outcomes than the general population. 20% of patients with claudication will experience either a myocardial infarction (MI) or cerebrovascular accident (CVA) within their lifetime. Moreover, patients with diagnosis of claudication have a 5-year mortality rate of 10-15% due to the comorbidities associated with vascular disease. [@conte2015a]

------------------------------------------------------------------------

## Teaching Case

### Scenario

73 year old male with past medical history of hypertension, hyperlipidemia, and diabetes presents to clinic for pain in his lower extremities. Of note, he has smoked roughly one pack of cigarettes a day since he was 20 years old. He states that it is difficult for him to walk 3 blocks without having to stop which he finds particularly annoying. When asked where it hurts, he starts grabbing his calves. He describes an achy, cramping, and pain in his calves whenever he walks, mostly on the right side. He denies any new sores or wounds that are not healing.

### Exam

**HEENT:** pupils equal round reactive to light, no lymphadenopathy

**Cardiac:** Regular rate and rhythm (RRR)

**Pulmonary:** Clear to auscultation in all lung fields. No accessory muscle use.

**Abdominal:** Soft, non-tender, non-distended, no pulsatile masses felt.

**Vascular/Extremities:** Warm, no edema present. Minimal hair appreciated bilaterally. Non-palpable distal pulses. Bilateral femoral pulses appreciated. No wounds or sores noted.

### Imaging

**ABI:** Right: 0.7 Left: 0.65

### Discussion Points

::: callout-note
## N.B. There is no prepared answers for the questions below.

However, we feel this chapter contains all the necessary information to answer the questions. If not, please let us know!
:::

1.  Please explain the pathophysiology for the patient's lower extremity pain and discomfort.
2.  Please list the patient's risk factors for peripheral arterial disease. What is the best medical management to optimize the these risk factors?
3.  What initial testing would you want to obtain and why?
4.  What would be the first line of treatment for patients with symptomatic claudication after medical management?

------------------------------------------------------------------------

## Key Articles

1.  Conte MS, Pomposelli FB, Clair DG, et al. Society for Vascular Surgery practice guidelines for atherosclerotic occlusive disease of the lower extremities: Management of asymptomatic disease and claudication. Journal of Vascular Surgery. 2015;61(3):2S-41S.e1. doi:10.1016/j.jvs.2014.12.009[@conte2015b]

2.  Conte MS, Bradbury AW, Kolh P, et al. Global vascular guidelines on the management of chronic limb-threatening ischemia. Journal of Vascular Surgery. 2019;69(6):3S-125S.e40. doi:10.1016/j.jvs.2019.02.016[@conte2019a]

3.  Gerhard-Herman MD, Gornik HL, Barrett C, et al. 2016 AHA/ACC Guideline on the Management of Patients With Lower Extremity Peripheral Artery Disease: Executive Summary: A Report of the American College of Cardiology/American Heart Association Task Force on Clinical Practice Guidelines. Circulation. 2017;135(12). doi:10.1161/CIR.0000000000000470[@gerhard-herman2017]

4.  Khan TH, Farooqui FA, Niazi K. Critical review of the ankle brachial index. Curr Cardiol Rev. 2008 May;4(2):101-6. doi: 10.2174/157340308784245810. PMID: 19936284; PMCID: PMC2779349.[@khan2008]

5.  McDermott MM, Criqui MH. Ankle-Brachial Index Screening and Improving Peripheral Artery Disease Detection and Outcomes. JAMA. 2018;320(2):143. doi:10.1001/jama.2018.8953[@mcdermott2018]

------------------------------------------------------------------------

## Additional Resources

### Audible Bleeding Content

-   Audible Bleeding Exam Prep: [Medical Management and Claudication Chapter](https://adam-mdmph.quarto.pub/vascular-surgery-exam-prep/claudication.html)
-   Caitlin W. Hicks, MD, MS - Overuse of early peripheral vascular interventions in claudication. Listen to it below and find [additional information here](https://www.audiblebleeding.com/hicks/), or find the episode wherever you listen to podcasts.<iframe title="Libsyn Player" style="border: none" src="//html5-player.libsyn.com/embed/episode/id/11570630/height/90/theme/custom/thumbnail/yes/direction/backward/render-playlist/no/custom-color/980c0c/" height="90" width="100%" scrolling="no"  allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>
-   VSITE Review - Peripheral Arterial Occlusive Disease (Part One). Listen to it below and find [additional information here](https://www.audiblebleeding.com/vsite-paod1/), or find the episode wherever you listen to podcasts.<iframe title="Libsyn Player" style="border: none" src="//html5-player.libsyn.com/embed/episode/id/15742403/height/90/theme/custom/thumbnail/yes/direction/backward/render-playlist/no/custom-color/980c0c/" height="90" width="100%" scrolling="no"  allowfullscreen webkitallowfullscreen mozallowfullscreen oallowfullscreen msallowfullscreen></iframe>

------------------------------------------------------------------------

### Gore Combat Manual

The [Gore Medical Vascular and Endovascular Surgery Combat Manual](https://www.goremedical.com/combat-manual) is an informative and entertaining read intended as a vascular surgery crash course for medical students, residents, and fellows alike. Highly accessible with a thoughtfully determined level of detail, but lacking in learning activities (e.g. questions, videos, etc.), this resource is a wonderful complement to the APDVS eBook.

::: callout-tip
Please see pages 85-90.
:::

------------------------------------------------------------------------

<!-- Google tag (gtag.js) -->

```{=html}
<script async src="https://www.googletagmanager.com/gtag/js?id=G-WS28VX4802"></script>
```
```{=html}
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-WS28VX4802');
</script>
```
